import Head from "next/head";
import styled from "@emotion/styled";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Futurama : The Animations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>Shut up and take my time!</h1>
        <p>Do not watch too much at home</p>
        <Gif src="/image/money.gif" alt="shut-up-gif" />
      </Main>
    </div>
  );
}

const Main = styled.main``;

const Gif = styled.img`
  width: 1000px;
`;
