import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Futurama : The Animations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Shut up and take my time!</h1>
        <p>Do not watch too much at home</p>
      </main>
    </div>
  );
}
